#!/bin/bash
# This script is used to test the breakpoint command (breakpoint and m)
#
# 
# ================================================================
# THIS SECTION IS SAME FOR EACH TEST SCRIPT - DO NOT CHANGE IT
#
# get the script folder
pushd `dirname $0` > /dev/null
mydir=`pwd`
popd > /dev/null

# get the parent folder of the script. The common script is supposed to be there.
# script folder
comm_file_dir="$(dirname "$mydir")"

# load the common file so that we could call the function "test_it"
source "${comm_file_dir}/test_common"

# 
# ================================================
#
# test case 1 - breakpoint
#
test_title="Testing command - breakpoint"
src_file="${mydir}/breakpoint"
cmd_file="${mydir}/breakpoint.cmd"
expected=("x = 1;")
unexpected=("y = 2;")

echo "$test_title"
test_it "$src_file" "$cmd_file" expected unexpected

