# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/integration/typescript-npm"
    schedule:
      interval: "weekly"
    # When Dependabot updates package.json, the maintainer must also update
    # integration/typescript-npm/packages.sh with new SHA256 hashes. See
    # integration/typescript-npm/README.md for instructions.
    commit-message:
      prefix: "npm-integration"
