#!/bin/bash
# This script is used to test the step out command (out/so/step --out)
#
# 
# ================================================================
# THIS SECTION IS SAME FOR EACH TEST SCRIPT - DO NOT CHANGE IT
#
# get the script folder
pushd `dirname $0` > /dev/null
mydir=`pwd`
popd > /dev/null

# get the parent folder of the script. The common script is supposed to be there.
# script folder
comm_file_dir="$(dirname "$mydir")"

# load the common file so that we could call the function "test_it"
source "${comm_file_dir}/test_common"

# 
# ================================================
#
# test case 1 - step --out
#
test_title="Testing command - step --out"
src_file="${mydir}/step_out"
cmd_file="${mydir}/step_out.cmd"
expected=(" __CPROVER_pipe_count = (unsigned int)0" "main();")
unexpected=("i = 1234;")

echo "$test_title"
test_it "$src_file" "$cmd_file" expected unexpected

#
# test case 2 - out
#
test_title="Testing command - out"
cmd_file="${mydir}/out.cmd"

echo "$test_title"
test_it "$src_file" "$cmd_file" expected unexpected

#
# test case 3 - so
#
test_title="Testing command - so"
cmd_file="${mydir}/so.cmd"

echo "$test_title"
test_it "$src_file" "$cmd_file" expected unexpected


exit
