#!/bin/bash
# This script is used to test the quit command
#

echo TESTING the quit command

cat << EOF > test.c
int main()
{
	return 0;
}
EOF

goto-cc -o test.bin test.c

if [ $? -ne 0 ]
then
    echo 
    echo "Compile failed, please fix the script and re-run it."
    exit 1
fi

# 
# generate command file to test_input
echo q > test_input

# now run the interpreter. It reads input from test_input
# 
output=$( goto-instrument test.bin --interpreter < test_input \
    | sed -n "/Starting interpreter/p;/__CPROVER_initialize();/p" \
    | wc -l )

# display passed info    
[[ "$output" = "2" ]] && echo "q - PASSED" || echo "q - NOT PASSED"

# test quit
echo quit > test_input
output=$( goto-instrument test.bin --interpreter < test_input \
    | sed -n "/Starting interpreter/p;/__CPROVER_initialize();/p" \
    | wc -l )
[[ "$output" = "2" ]] && echo "quit - PASSED" || echo "quit - NOT PASSED"

# clean up
rm test.c
rm test.bin
rm test_input
