#!/bin/bash
# This script is used to test the save command (run directly to the save function)
#
# 
# ================================================================
# THIS SECTION IS SAME FOR EACH TEST SCRIPT - DO NOT CHANGE IT
#
# get the script folder
pushd `dirname $0` > /dev/null
mydir=`pwd`
popd > /dev/null

# get the parent folder of the script. The common script is supposed to be there.
# script folder
comm_file_dir="$(dirname "$mydir")"

# load the common file so that we could call the save "test_it"
source "${comm_file_dir}/test_common"

# 
# ================================================
#
# test case 1 - save
#
test_title="Testing the save command"
src_file="${mydir}/save"
cmd_file="${mydir}/save.cmd"
expected=("saved to 'savef.tmp'")
unexpected=()

if [  -f savef.tmp ]; then
    rm savef.tmp
fi

echo "$test_title"
test_it "$src_file" "$cmd_file" expected unexpected

if [  -f savef.tmp ]; then
    rm savef.tmp
fi