#!/bin/bash
# This script is used to test the printf command (printf and q)
#
# 
# ================================================================
# THIS SECTION IS SAME FOR EACH TEST SCRIPT - DO NOT CHANGE IT
#
# get the script folder
pushd `dirname $0` > /dev/null
mydir=`pwd`
popd > /dev/null

# get the parent folder of the script. The common script is supposed to be there.
# script folder
comm_file_dir="$(dirname "$mydir")"

# load the common file so that we could call the function "test_it"
source "${comm_file_dir}/test_common"

# 
# ================================================
#
# test case 1 - printf
#
test_title="Testing C printf()"
src_file="${mydir}/printf"
cmd_file="${mydir}/printf.cmd"
expected=("i: 100" "j: 200" "f: 12.34" "d: 45.67" "c: x" "msg: Hello" "i==100, j==200, f==12.34, d==45.67, c==x, msg==Hello")
unexpected=()

echo "$test_title"
test_it "$src_file" "$cmd_file" expected unexpected

exit
