#!/bin/bash
# This script is used to test the print command (print and p)
#

echo TESTING the print command

# compile
goto-cc -o print.o print_src.c

if [ $? -ne 0 ]
then
    echo 
    echo "Compile failed, please fix the source file and re-run this script."
    exit 1
fi

# now run the interpreter. It reads input from test_input
# 
output=$( goto-instrument print.o --interpreter < print_input_p \
    | sed -n "/Starting interpreter/p;/__CPROVER_initialize();/p" \
    | wc -l )

# display passed info    
[[ "$output" = "2" ]] && echo "p - PASSED" || echo "p - NOT PASSED"

# test print
output=$( goto-instrument print.o --interpreter < print_input_print \
    | sed -n "/Starting interpreter/p;/__CPROVER_initialize();/p" \
    | wc -l )
[[ "$output" = "2" ]] && echo "print - PASSED" || echo "print - NOT PASSED"
