#!/bin/bash
# This script is used to test the go command
#
# 
# ================================================================
# THIS SECTION IS SAME FOR EACH TEST SCRIPT - DO NOT CHANGE IT
#
# get the script folder
pushd `dirname $0` > /dev/null
mydir=`pwd`
popd > /dev/null

# get the parent folder of the script. The common script is supposed to be there.
# script folder
comm_file_dir="$(dirname "$mydir")"

# load the common file so that we could call the function "test_it"
source "${comm_file_dir}/test_common"

# 
# ================================================
#
# test case 1 - go
#
test_title="Testing command - go"
src_file="${mydir}/go_src"
cmd_file="${mydir}/go_cmd_go"
expected=("return 123;" "That is the end")
unexpected=()

echo "$test_title"
test_it "$src_file" "$cmd_file" expected unexpected

exit
