#!/bin/bash
# This script is used to test the next command (next and n)
#
# 
# ================================================================
# THIS SECTION IS SAME FOR EACH TEST SCRIPT - DO NOT CHANGE IT
#
# get the script folder
pushd `dirname $0` > /dev/null
mydir=`pwd`
popd > /dev/null

# get the parent folder of the script. The common script is supposed to be there.
# script folder
comm_file_dir="$(dirname "$mydir")"

# load the common file so that we could call the function "test_it"
source "${comm_file_dir}/test_common"

# 
# ================================================
#
# test case 1 - step --into
#
test_title="Testing command - step --into"
src_file="${mydir}/step_into_src"
cmd_file="${mydir}/step_into_cmd"
expected=(" __CPROVER_pipe_count = (unsigned int)0")
unexpected=("main();")

echo "$test_title"
test_it "$src_file" "$cmd_file" expected unexpected

#
# test case 2 - into
#
test_title="Testing command - into"
cmd_file="${mydir}/step_into_cmd_into"

echo "$test_title"
test_it "$src_file" "$cmd_file" expected unexpected

#
# test case 3 - si
#
test_title="Testing command - si"
cmd_file="${mydir}/step_into_cmd_si"

echo "$test_title"
test_it "$src_file" "$cmd_file" expected unexpected

exit
