#!/bin/bash
# This script is used to test the quit command (quit and q)
#

echo TESTING the quit command

# compile
goto-cc -o quit.o quit_src.c

if [ $? -ne 0 ]
then
    echo 
    echo "Compile failed, please fix the source file and re-run this script."
    exit 1
fi

# now run the interpreter. It reads input from test_input
# 
output=$( goto-instrument quit.o --interpreter < quit_input_q \
    | sed -n "/Starting interpreter/p;/__CPROVER_initialize();/p" \
    | wc -l )

# display passed info    
[[ "$output" = "2" ]] && echo "q - PASSED" || echo "q - NOT PASSED"

# test quit
output=$( goto-instrument quit.o --interpreter < quit_input_quit \
    | sed -n "/Starting interpreter/p;/__CPROVER_initialize();/p" \
    | wc -l )
[[ "$output" = "2" ]] && echo "quit - PASSED" || echo "quit - NOT PASSED"
