#!/bin/bash
# This script is used to test the where command (run directly to the where function)
#
# 
# ================================================================
# THIS SECTION IS SAME FOR EACH TEST SCRIPT - DO NOT CHANGE IT
#
# get the script folder
pushd `dirname $0` > /dev/null
mydir=`pwd`
popd > /dev/null

# get the parent folder of the script. The common script is supposed to be there.
# script folder
comm_file_dir="$(dirname "$mydir")"

# load the common file so that we could call the where "test_it"
source "${comm_file_dir}/test_common"

# 
# ================================================
#
# test case 1 - where
#
test_title="Testing the where command"
src_file="${mydir}/where"
cmd_file="${mydir}/where.cmd"
expected=("int x")
unexpected=()

echo "$test_title"
test_it "$src_file" "$cmd_file" expected unexpected
