#!/bin/bash
# This script is used to test the next command (next and n)
#
# 
# ================================================================
# THIS SECTION IS SAME FOR EACH TEST SCRIPT - DO NOT CHANGE IT
#
# get the script folder
pushd `dirname $0` > /dev/null
mydir=`pwd`
popd > /dev/null

# get the parent folder of the script. The common script is supposed to be there.
# script folder
comm_file_dir="$(dirname "$mydir")"

# load the common file so that we could call the function "test_it"
source "${comm_file_dir}/test_common"

# 
# ================================================
#
# test case 1 - silent
# 
test_title="Testing command - silent"
src_file="${mydir}/silent_src"
cmd_file="${mydir}/silent_cmd_silent"
debug_flag="no"  # set this to yes to preserve compiled files
expected=("int i;")
unexpected=("i = 123;")

echo "$test_title"
test_it "$src_file" "$cmd_file" "$debug_flag" expected unexpected

#
# test case 2 - silent --on
#
test_title="Testing command - silent --on"
src_file="${mydir}/silent_src"
cmd_file="${mydir}/silent_cmd_silent_on"
debug_flag="no"  # set this to yes to preserve compiled files
expected=("int i;")
unexpected=("i = 123;")

echo "$test_title"
test_it "$src_file" "$cmd_file" "$debug_flag" expected unexpected

#
# test case 3 - son
# 
test_title="Testing command - son"
src_file="${mydir}/silent_src"
cmd_file="${mydir}/silent_cmd_son"
debug_flag="no"  # set this to yes to preserve compiled files
expected=("int i;")
unexpected=("i = 123;")

echo "$test_title"
test_it "$src_file" "$cmd_file" "$debug_flag" expected unexpected

#
# test case 4 - silent --off
# 
test_title="Testing command - silent --off"
src_file="${mydir}/silent_src"
cmd_file="${mydir}/silent_cmd_silent_off"
debug_flag="no"  # set this to yes to preserve compiled files
expected=("int i;" "i = 456")
unexpected=("bad command" "i = 123;")

echo "$test_title"
test_it "$src_file" "$cmd_file" "$debug_flag" expected unexpected
