#!/bin/bash
# This script is used to test the quit command (quit and q)
#
# 
# ================================================================
# THIS SECTION IS SAME FOR EACH TEST SCRIPT - DO NOT CHANGE IT
#
# get the script folder
pushd `dirname $0` > /dev/null
mydir=`pwd`
popd > /dev/null

# get the parent folder of the script. The common script is supposed to be there.
# script folder
comm_file_dir="$(dirname "$mydir")"

# load the common file so that we could call the function "test_it"
source "${comm_file_dir}/test_common"

# 
# ================================================
#
# test case 1 - quit
#
test_title="Testing command - quit"
src_file="${mydir}/quit_src"
cmd_file="${mydir}/quit_cmd_quit"
expected=("Starting interpreter" "__CPROVER_initialize();")
unexpected=()

echo "$test_title"
test_it "$src_file" "$cmd_file" expected unexpected

#
# test case 2 - q
#
test_title="Testing command - q"
cmd_file="${mydir}/quit_cmd_q"

echo "$test_title"
test_it "$src_file" "$cmd_file" expected unexpected

exit
