#!/bin/bash
# This script is used to test the next command (next and n)
#
# 
# ================================================================
# THIS SECTION IS SAME FOR EACH TEST SCRIPT - DO NOT CHANGE IT
#
# get the script folder
pushd `dirname $0` > /dev/null
mydir=`pwd`
popd > /dev/null

# get the parent folder of the script. The common script is supposed to be there.
# script folder
comm_file_dir="$(dirname "$mydir")"

# load the common file so that we could call the function "test_it"
source "${comm_file_dir}/test_common"

# 
# ================================================
#
# test case 1 - next
#
test_title="Testing command - next"
src_file="${mydir}/next_src"
cmd_file="${mydir}/next_cmd_next"
debug_flag="no"  # set this to yes to preserve compiled files
expected=("main();")
unexpected=()

echo "$test_title"
test_it "$src_file" "$cmd_file" "$debug_flag" expected unexpected

#
# test case 2 - n
#
test_title="Testing command - n"
# src_file="${mydir}/next_src"
cmd_file="${mydir}/next_cmd_n"

echo "$test_title"
test_it "$src_file" "$cmd_file" "$debug_flag" expected unexpected

exit
