name: Python stdlib parse integration test

on:
  pull_request:
    branches: [ develop ]

jobs:
  # This job takes approximately 10 minutes.
  python-stdlib-parse:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive
      - name: Fetch dependencies
        env:
          # This is needed in addition to -yq to prevent apt-get from asking
          # for user input.
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo apt-get update
          sudo apt-get install --no-install-recommends -y build-essential flex bison maven ccache clang-19 clang++-19 python3
          make -C src minisat2-download
      - name: Prepare ccache
        uses: actions/cache@v5
        with:
          save-always: true
          path: .ccache
          key: ${{ runner.os }}-24.04-make-clang-${{ github.ref }}-${{ github.sha }}-PYSTDLIB
          restore-keys: |
            ${{ runner.os }}-24.04-make-clang-${{ github.ref }}
            ${{ runner.os }}-24.04-make-clang
      - name: ccache environment
        run: |
          echo "CCACHE_BASEDIR=$PWD" >> $GITHUB_ENV
          echo "CCACHE_DIR=$PWD/.ccache" >> $GITHUB_ENV
      - name: Zero ccache stats and limit in size
        run: ccache -z --max-size=500M
      - name: Build cbmc
        run: |
          make -C src CXX='ccache /usr/bin/clang++' cbmc.dir -j4
      - name: Print ccache stats
        run: ccache -s
      - name: Run Python stdlib parse integration test
        run: |
          CBMC="$PWD/src/cbmc/cbmc" integration/python-stdlib/run_stdlib_parse_test.sh
